# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    region         = "eu-central-1"
    bucket         = "terraformstatebucket58366"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "./terragruntstatefile"
  }
}
