name: 'Terraform-workflow'

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
    
jobs:

  build-and-test:
    uses: LuckyDucky583/terraform-github-actions/.github/workflows/.terraform-aws.yml@v1.0.0
    with:
      working-directory: ./src/infrastructure/envs/demo
    secrets: inherit
