name: 'Terraform-workflow'

on:
  push:
    branches:
    - main
    - dev
    
jobs:

  terraform:
    uses: LuckyDucky583/terraform-github-actions/.github/workflows/.terraform-aws-pull-request.yml@v1.0.1
    with:
      working-directory: ./src/infrastructure/envs/demo
    secrets: inherit
