name: 'Terraform-workflow'

on:
  pull_request:
    branches:
    - main
    - dev
    
jobs:

  terraform:
    uses: LuckyDucky583/terraform-github-actions/.github/workflows/.terraform-aws-pull-request.yml@v0.1.0
    with:
      working-directory: ./src/infrastructure/envs/demo
    secrets: inherit
