name: 'Terraform-workflow'

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
    
jobs:
  run-terraform-workflow:
      uses: LuckyDucky583/terraform-github-actions/.github/workflows/.terraform-aws.yml@feat/change-folder-structure
      with:
        working-directory: ./src/infrastructure/envs/demo