name: 'Terraform-workflow'

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

jobs:
  run-terraform-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: run-terraform 
        uses: LuckyDucky583/terraform-github-actions/terraform@feat/change-folder-structure